variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "region" {}
variable "functionname" {}
variable "handler_name" {}
variable "runtime_name" {}
variable "s3_bucket_name" {}
variable "s3_file_name" {}
variable "accountid" {}
variable "lambda_role" {}
variable "job_queue_name" {}
variable "jobdef_name" {}
variable "client_accountid" {}
variable "redshift_url" {}
variable "event_name1" {}
variable "event_name2" {}
variable "targetid" {}
variable "redshift_info" {}
variable "inventory" {}
variable "backup" {}
variable "baseaccountrole" {}
variable "rds_url" {}
variable "rds_info" {}
variable "es_url" {}
variable "alb_url" {}
