//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.10 at 12:51:21 PM PDT 
//


package com.tmobile.cso.pacman.qualys.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RESPONSE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="HOST_LIST">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="HOST" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="IP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TRACKING_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OS_CPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="DNS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="QG_HOSTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="LAST_SCAN_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                       &lt;element name="LAST_VM_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                       &lt;element name="LAST_VM_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                                       &lt;element name="LAST_VM_AUTH_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                       &lt;element name="LAST_VM_AUTH_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                                       &lt;element name="DETECTION_LIST">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="DETECTION">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="QID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                           &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="SEVERITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                           &lt;element name="RESULTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="FIRST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                           &lt;element name="LAST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                           &lt;element name="TIMES_FOUND" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                           &lt;element name="IS_DISABLED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                           &lt;element name="LAST_PROCESSED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "HOST_LIST_VM_DETECTION_OUTPUT")
public class HOSTLISTVMDETECTIONOUTPUT {

    @XmlElement(name = "RESPONSE", required = true)
    protected HOSTLISTVMDETECTIONOUTPUT.RESPONSE response;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE }
     *     
     */
    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE getRESPONSE() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE }
     *     
     */
    public void setRESPONSE(HOSTLISTVMDETECTIONOUTPUT.RESPONSE value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="HOST_LIST">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="HOST" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="IP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TRACKING_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OS_CPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="DNS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="QG_HOSTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="LAST_SCAN_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                             &lt;element name="LAST_VM_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                             &lt;element name="LAST_VM_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                             &lt;element name="LAST_VM_AUTH_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                             &lt;element name="LAST_VM_AUTH_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                             &lt;element name="DETECTION_LIST">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="DETECTION">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="QID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                                 &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="SEVERITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                                 &lt;element name="RESULTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="FIRST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                                                 &lt;element name="LAST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                                                 &lt;element name="TIMES_FOUND" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                                 &lt;element name="IS_DISABLED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                                 &lt;element name="LAST_PROCESSED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datetime",
        "hostlist"
    })
    public static class RESPONSE {

        @XmlElement(name = "DATETIME", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar datetime;
        @XmlElement(name = "HOST_LIST", required = true)
        protected HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST hostlist;

        /**
         * Gets the value of the datetime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATETIME() {
            return datetime;
        }

        /**
         * Sets the value of the datetime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATETIME(XMLGregorianCalendar value) {
            this.datetime = value;
        }

        /**
         * Gets the value of the hostlist property.
         * 
         * @return
         *     possible object is
         *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST }
         *     
         */
        public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST getHOSTLIST() {
            return hostlist;
        }

        /**
         * Sets the value of the hostlist property.
         * 
         * @param value
         *     allowed object is
         *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST }
         *     
         */
        public void setHOSTLIST(HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST value) {
            this.hostlist = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="HOST" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="IP" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TRACKING_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OS_CPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="DNS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="QG_HOSTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="LAST_SCAN_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                   &lt;element name="LAST_VM_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                   &lt;element name="LAST_VM_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *                   &lt;element name="LAST_VM_AUTH_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                   &lt;element name="LAST_VM_AUTH_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *                   &lt;element name="DETECTION_LIST">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="DETECTION">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="QID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                       &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="SEVERITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                       &lt;element name="RESULTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="FIRST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                                       &lt;element name="LAST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                                       &lt;element name="TIMES_FOUND" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                                       &lt;element name="IS_DISABLED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                                       &lt;element name="LAST_PROCESSED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "host"
        })
        public static class HOSTLIST {

            @XmlElement(name = "HOST")
            protected List<HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST> host;

            /**
             * Gets the value of the host property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the host property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHOST().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST }
             * 
             * 
             */
            public List<HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST> getHOST() {
                if (host == null) {
                    host = new ArrayList<HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST>();
                }
                return this.host;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="IP" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TRACKING_METHOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OS_CPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="DNS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="QG_HOSTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="LAST_SCAN_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *         &lt;element name="LAST_VM_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *         &lt;element name="LAST_VM_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
             *         &lt;element name="LAST_VM_AUTH_SCANNED_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *         &lt;element name="LAST_VM_AUTH_SCANNED_DURATION" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
             *         &lt;element name="DETECTION_LIST">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="DETECTION">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="QID" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                             &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="SEVERITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                             &lt;element name="RESULTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="FIRST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *                             &lt;element name="LAST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *                             &lt;element name="TIMES_FOUND" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                             &lt;element name="IS_DISABLED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                             &lt;element name="LAST_PROCESSED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "ip",
                "trackingmethod",
                "os",
                "oscpe",
                "dns",
                "qghostid",
                "lastscandatetime",
                "lastvmscanneddate",
                "lastvmscannedduration",
                "lastvmauthscanneddate",
                "lastvmauthscannedduration",
                "detectionlist"
            })
            public static class HOST {

                @XmlElement(name = "ID")
                protected long id;
                @XmlElement(name = "IP", required = true)
                protected String ip;
                @XmlElement(name = "TRACKING_METHOD", required = true)
                protected String trackingmethod;
                @XmlElement(name = "OS", required = true)
                protected String os;
                @XmlElement(name = "OS_CPE")
                protected String oscpe;
                @XmlElement(name = "DNS", required = true)
                protected String dns;
                @XmlElement(name = "QG_HOSTID")
                protected String qghostid;
                @XmlElement(name = "LAST_SCAN_DATETIME", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar lastscandatetime;
                @XmlElement(name = "LAST_VM_SCANNED_DATE", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar lastvmscanneddate;
                @XmlElement(name = "LAST_VM_SCANNED_DURATION")
                protected Short lastvmscannedduration;
                @XmlElement(name = "LAST_VM_AUTH_SCANNED_DATE", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar lastvmauthscanneddate;
                @XmlElement(name = "LAST_VM_AUTH_SCANNED_DURATION")
                protected Short lastvmauthscannedduration;
                @XmlElement(name = "DETECTION_LIST", required = true)
                protected HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST detectionlist;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public long getID() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setID(long value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the ip property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIP() {
                    return ip;
                }

                /**
                 * Sets the value of the ip property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIP(String value) {
                    this.ip = value;
                }

                /**
                 * Gets the value of the trackingmethod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTRACKINGMETHOD() {
                    return trackingmethod;
                }

                /**
                 * Sets the value of the trackingmethod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTRACKINGMETHOD(String value) {
                    this.trackingmethod = value;
                }

                /**
                 * Gets the value of the os property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOS() {
                    return os;
                }

                /**
                 * Sets the value of the os property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOS(String value) {
                    this.os = value;
                }

                /**
                 * Gets the value of the oscpe property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOSCPE() {
                    return oscpe;
                }

                /**
                 * Sets the value of the oscpe property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOSCPE(String value) {
                    this.oscpe = value;
                }

                /**
                 * Gets the value of the dns property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDNS() {
                    return dns;
                }

                /**
                 * Sets the value of the dns property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDNS(String value) {
                    this.dns = value;
                }

                /**
                 * Gets the value of the qghostid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQGHOSTID() {
                    return qghostid;
                }

                /**
                 * Sets the value of the qghostid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQGHOSTID(String value) {
                    this.qghostid = value;
                }

                /**
                 * Gets the value of the lastscandatetime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getLASTSCANDATETIME() {
                    return lastscandatetime;
                }

                /**
                 * Sets the value of the lastscandatetime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setLASTSCANDATETIME(XMLGregorianCalendar value) {
                    this.lastscandatetime = value;
                }

                /**
                 * Gets the value of the lastvmscanneddate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getLASTVMSCANNEDDATE() {
                    return lastvmscanneddate;
                }

                /**
                 * Sets the value of the lastvmscanneddate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setLASTVMSCANNEDDATE(XMLGregorianCalendar value) {
                    this.lastvmscanneddate = value;
                }

                /**
                 * Gets the value of the lastvmscannedduration property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getLASTVMSCANNEDDURATION() {
                    return lastvmscannedduration;
                }

                /**
                 * Sets the value of the lastvmscannedduration property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setLASTVMSCANNEDDURATION(Short value) {
                    this.lastvmscannedduration = value;
                }

                /**
                 * Gets the value of the lastvmauthscanneddate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getLASTVMAUTHSCANNEDDATE() {
                    return lastvmauthscanneddate;
                }

                /**
                 * Sets the value of the lastvmauthscanneddate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setLASTVMAUTHSCANNEDDATE(XMLGregorianCalendar value) {
                    this.lastvmauthscanneddate = value;
                }

                /**
                 * Gets the value of the lastvmauthscannedduration property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getLASTVMAUTHSCANNEDDURATION() {
                    return lastvmauthscannedduration;
                }

                /**
                 * Sets the value of the lastvmauthscannedduration property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setLASTVMAUTHSCANNEDDURATION(Short value) {
                    this.lastvmauthscannedduration = value;
                }

                /**
                 * Gets the value of the detectionlist property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST }
                 *     
                 */
                public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST getDETECTIONLIST() {
                    return detectionlist;
                }

                /**
                 * Sets the value of the detectionlist property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST }
                 *     
                 */
                public void setDETECTIONLIST(HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST value) {
                    this.detectionlist = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="DETECTION">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="QID" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                   &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="SEVERITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                   &lt;element name="RESULTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="FIRST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                 *                   &lt;element name="LAST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                 *                   &lt;element name="TIMES_FOUND" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *                   &lt;element name="IS_DISABLED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *                   &lt;element name="LAST_PROCESSED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "detection"
                })
                public static class DETECTIONLIST {

                    @XmlElement(name = "DETECTION", required = true)
                    protected HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION detection;

                    /**
                     * Gets the value of the detection property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION }
                     *     
                     */
                    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION getDETECTION() {
                        return detection;
                    }

                    /**
                     * Sets the value of the detection property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION }
                     *     
                     */
                    public void setDETECTION(HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION value) {
                        this.detection = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="QID" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="SEVERITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *         &lt;element name="RESULTS" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="FIRST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                     *         &lt;element name="LAST_FOUND_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                     *         &lt;element name="TIMES_FOUND" type="{http://www.w3.org/2001/XMLSchema}short"/>
                     *         &lt;element name="IS_DISABLED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                     *         &lt;element name="LAST_PROCESSED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "qid",
                        "type",
                        "severity",
                        "results",
                        "firstfounddatetime",
                        "lastfounddatetime",
                        "timesfound",
                        "isdisabled",
                        "lastprocesseddatetime"
                    })
                    public static class DETECTION {

                        @XmlElement(name = "QID")
                        protected int qid;
                        @XmlElement(name = "TYPE", required = true)
                        protected String type;
                        @XmlElement(name = "SEVERITY")
                        protected byte severity;
                        @XmlElement(name = "RESULTS", required = true)
                        protected String results;
                        @XmlElement(name = "FIRST_FOUND_DATETIME", required = true)
                        @XmlSchemaType(name = "dateTime")
                        protected XMLGregorianCalendar firstfounddatetime;
                        @XmlElement(name = "LAST_FOUND_DATETIME", required = true)
                        @XmlSchemaType(name = "dateTime")
                        protected XMLGregorianCalendar lastfounddatetime;
                        @XmlElement(name = "TIMES_FOUND")
                        protected short timesfound;
                        @XmlElement(name = "IS_DISABLED")
                        protected byte isdisabled;
                        @XmlElement(name = "LAST_PROCESSED_DATETIME", required = true)
                        @XmlSchemaType(name = "dateTime")
                        protected XMLGregorianCalendar lastprocesseddatetime;

                        /**
                         * Gets the value of the qid property.
                         * 
                         */
                        public int getQID() {
                            return qid;
                        }

                        /**
                         * Sets the value of the qid property.
                         * 
                         */
                        public void setQID(int value) {
                            this.qid = value;
                        }

                        /**
                         * Gets the value of the type property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getTYPE() {
                            return type;
                        }

                        /**
                         * Sets the value of the type property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setTYPE(String value) {
                            this.type = value;
                        }

                        /**
                         * Gets the value of the severity property.
                         * 
                         */
                        public byte getSEVERITY() {
                            return severity;
                        }

                        /**
                         * Sets the value of the severity property.
                         * 
                         */
                        public void setSEVERITY(byte value) {
                            this.severity = value;
                        }

                        /**
                         * Gets the value of the results property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRESULTS() {
                            return results;
                        }

                        /**
                         * Sets the value of the results property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRESULTS(String value) {
                            this.results = value;
                        }

                        /**
                         * Gets the value of the firstfounddatetime property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public XMLGregorianCalendar getFIRSTFOUNDDATETIME() {
                            return firstfounddatetime;
                        }

                        /**
                         * Sets the value of the firstfounddatetime property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public void setFIRSTFOUNDDATETIME(XMLGregorianCalendar value) {
                            this.firstfounddatetime = value;
                        }

                        /**
                         * Gets the value of the lastfounddatetime property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public XMLGregorianCalendar getLASTFOUNDDATETIME() {
                            return lastfounddatetime;
                        }

                        /**
                         * Sets the value of the lastfounddatetime property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public void setLASTFOUNDDATETIME(XMLGregorianCalendar value) {
                            this.lastfounddatetime = value;
                        }

                        /**
                         * Gets the value of the timesfound property.
                         * 
                         */
                        public short getTIMESFOUND() {
                            return timesfound;
                        }

                        /**
                         * Sets the value of the timesfound property.
                         * 
                         */
                        public void setTIMESFOUND(short value) {
                            this.timesfound = value;
                        }

                        /**
                         * Gets the value of the isdisabled property.
                         * 
                         */
                        public byte getISDISABLED() {
                            return isdisabled;
                        }

                        /**
                         * Sets the value of the isdisabled property.
                         * 
                         */
                        public void setISDISABLED(byte value) {
                            this.isdisabled = value;
                        }

                        /**
                         * Gets the value of the lastprocesseddatetime property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public XMLGregorianCalendar getLASTPROCESSEDDATETIME() {
                            return lastprocesseddatetime;
                        }

                        /**
                         * Sets the value of the lastprocesseddatetime property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public void setLASTPROCESSEDDATETIME(XMLGregorianCalendar value) {
                            this.lastprocesseddatetime = value;
                        }

                    }

                }

            }

        }

    }

}
