//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.08 at 02:42:29 PM PDT 
//

package com.tmobile.cso.pacman.qualys.dto;

import javax.xml.bind.annotation.XmlRegistry;




/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: generated.
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceResponse }.
     *
     * @return the service response
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data }
     *
     * @return the data
     */
    public ServiceResponse.Data createServiceResponseData() {
        return new ServiceResponse.Data();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset }
     *
     * @return the host asset
     */
    public ServiceResponse.Data.HostAsset createServiceResponseDataHostAsset() {
        return new ServiceResponse.Data.HostAsset();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.NetworkInterface }
     *
     * @return the network interface
     */
    public ServiceResponse.Data.HostAsset.NetworkInterface createServiceResponseDataHostAssetNetworkInterface() {
        return new ServiceResponse.Data.HostAsset.NetworkInterface();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.NetworkInterface.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.NetworkInterface.List createServiceResponseDataHostAssetNetworkInterfaceList() {
        return new ServiceResponse.Data.HostAsset.NetworkInterface.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Account }
     *
     * @return the account
     */
    public ServiceResponse.Data.HostAsset.Account createServiceResponseDataHostAssetAccount() {
        return new ServiceResponse.Data.HostAsset.Account();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Account.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.Account.List createServiceResponseDataHostAssetAccountList() {
        return new ServiceResponse.Data.HostAsset.Account.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Volume }
     *
     * @return the volume
     */
    public ServiceResponse.Data.HostAsset.Volume createServiceResponseDataHostAssetVolume() {
        return new ServiceResponse.Data.HostAsset.Volume();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Volume.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.Volume.List createServiceResponseDataHostAssetVolumeList() {
        return new ServiceResponse.Data.HostAsset.Volume.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Processor }
     *
     * @return the processor
     */
    public ServiceResponse.Data.HostAsset.Processor createServiceResponseDataHostAssetProcessor() {
        return new ServiceResponse.Data.HostAsset.Processor();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Processor.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.Processor.List createServiceResponseDataHostAssetProcessorList() {
        return new ServiceResponse.Data.HostAsset.Processor.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Vuln }
     *
     * @return the vuln
     */
    public ServiceResponse.Data.HostAsset.Vuln createServiceResponseDataHostAssetVuln() {
        return new ServiceResponse.Data.HostAsset.Vuln();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Vuln.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.Vuln.List createServiceResponseDataHostAssetVulnList() {
        return new ServiceResponse.Data.HostAsset.Vuln.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Software }
     *
     * @return the software
     */
    public ServiceResponse.Data.HostAsset.Software createServiceResponseDataHostAssetSoftware() {
        return new ServiceResponse.Data.HostAsset.Software();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Software.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.Software.List createServiceResponseDataHostAssetSoftwareList() {
        return new ServiceResponse.Data.HostAsset.Software.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.OpenPort }
     *
     * @return the open port
     */
    public ServiceResponse.Data.HostAsset.OpenPort createServiceResponseDataHostAssetOpenPort() {
        return new ServiceResponse.Data.HostAsset.OpenPort();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.OpenPort.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.OpenPort.List createServiceResponseDataHostAssetOpenPortList() {
        return new ServiceResponse.Data.HostAsset.OpenPort.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.SourceInfo }
     *
     * @return the source info
     */
    public ServiceResponse.Data.HostAsset.SourceInfo createServiceResponseDataHostAssetSourceInfo() {
        return new ServiceResponse.Data.HostAsset.SourceInfo();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.SourceInfo.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.SourceInfo.List createServiceResponseDataHostAssetSourceInfoList() {
        return new ServiceResponse.Data.HostAsset.SourceInfo.List();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Tags }
     *
     * @return the tags
     */
    public ServiceResponse.Data.HostAsset.Tags createServiceResponseDataHostAssetTags() {
        return new ServiceResponse.Data.HostAsset.Tags();
    }

    /**
     * Create an instance of {@link ServiceResponse.Data.HostAsset.Tags.List }
     *
     * @return the list
     */
    public ServiceResponse.Data.HostAsset.Tags.List createServiceResponseDataHostAssetTagsList() {
        return new ServiceResponse.Data.HostAsset.Tags.List();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.NetworkInterface.List.HostAssetInterface }
     *
     * @return the host asset interface
     */
    public ServiceResponse.Data.HostAsset.NetworkInterface.List.HostAssetInterface createServiceResponseDataHostAssetNetworkInterfaceListHostAssetInterface() {
        return new ServiceResponse.Data.HostAsset.NetworkInterface.List.HostAssetInterface();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Account.List.HostAssetAccount }
     *
     * @return the host asset account
     */
    public ServiceResponse.Data.HostAsset.Account.List.HostAssetAccount createServiceResponseDataHostAssetAccountListHostAssetAccount() {
        return new ServiceResponse.Data.HostAsset.Account.List.HostAssetAccount();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Volume.List.HostAssetVolume }
     *
     * @return the host asset volume
     */
    public ServiceResponse.Data.HostAsset.Volume.List.HostAssetVolume createServiceResponseDataHostAssetVolumeListHostAssetVolume() {
        return new ServiceResponse.Data.HostAsset.Volume.List.HostAssetVolume();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Processor.List.HostAssetProcessor }
     *
     * @return the host asset processor
     */
    public ServiceResponse.Data.HostAsset.Processor.List.HostAssetProcessor createServiceResponseDataHostAssetProcessorListHostAssetProcessor() {
        return new ServiceResponse.Data.HostAsset.Processor.List.HostAssetProcessor();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Vuln.List.HostAssetVuln }
     *
     * @return the host asset vuln
     */
    public ServiceResponse.Data.HostAsset.Vuln.List.HostAssetVuln createServiceResponseDataHostAssetVulnListHostAssetVuln() {
        return new ServiceResponse.Data.HostAsset.Vuln.List.HostAssetVuln();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Software.List.HostAssetSoftware }
     *
     * @return the host asset software
     */
    public ServiceResponse.Data.HostAsset.Software.List.HostAssetSoftware createServiceResponseDataHostAssetSoftwareListHostAssetSoftware() {
        return new ServiceResponse.Data.HostAsset.Software.List.HostAssetSoftware();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.OpenPort.List.HostAssetOpenPort }
     *
     * @return the host asset open port
     */
    public ServiceResponse.Data.HostAsset.OpenPort.List.HostAssetOpenPort createServiceResponseDataHostAssetOpenPortListHostAssetOpenPort() {
        return new ServiceResponse.Data.HostAsset.OpenPort.List.HostAssetOpenPort();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.SourceInfo.List.AssetSource }
     *
     * @return the asset source
     */
    public ServiceResponse.Data.HostAsset.SourceInfo.List.AssetSource createServiceResponseDataHostAssetSourceInfoListAssetSource() {
        return new ServiceResponse.Data.HostAsset.SourceInfo.List.AssetSource();
    }

    /**
     * Create an instance of
     * {@link ServiceResponse.Data.HostAsset.Tags.List.TagSimple }
     *
     * @return the tag simple
     */
    public ServiceResponse.Data.HostAsset.Tags.List.TagSimple createServiceResponseDataHostAssetTagsListTagSimple() {
        return new ServiceResponse.Data.HostAsset.Tags.List.TagSimple();
    }
    
    /**
     * Create an instance of {@link HOSTLISTVMDETECTIONOUTPUT }
     * 
     */
    public HOSTLISTVMDETECTIONOUTPUT createHOSTLISTVMDETECTIONOUTPUT() {
        return new HOSTLISTVMDETECTIONOUTPUT();
    }

    /**
     * Create an instance of {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE }
     * 
     */
    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE createHOSTLISTVMDETECTIONOUTPUTRESPONSE() {
        return new HOSTLISTVMDETECTIONOUTPUT.RESPONSE();
    }

    /**
     * Create an instance of {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST }
     * 
     */
    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST createHOSTLISTVMDETECTIONOUTPUTRESPONSEHOSTLIST() {
        return new HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST();
    }

    /**
     * Create an instance of {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST }
     * 
     */
    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST createHOSTLISTVMDETECTIONOUTPUTRESPONSEHOSTLISTHOST() {
        return new HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST();
    }

    /**
     * Create an instance of {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST }
     * 
     */
    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST createHOSTLISTVMDETECTIONOUTPUTRESPONSEHOSTLISTHOSTDETECTIONLIST() {
        return new HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST();
    }

    /**
     * Create an instance of {@link HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION }
     * 
     */
    public HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION createHOSTLISTVMDETECTIONOUTPUTRESPONSEHOSTLISTHOSTDETECTIONLISTDETECTION() {
        return new HOSTLISTVMDETECTIONOUTPUT.RESPONSE.HOSTLIST.HOST.DETECTIONLIST.DETECTION();
    }

}
