FROM openjdk:8
ENV RUN_ARGS="--server.port=80 --server.ssl.enabled=false"
RUN apt update -y
RUN apt install python3-pip -y
RUN pip3 install awscli
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
#ENTRYPOINT ["./entrypoint.sh"]

